### ISSUE TITLE
Feature request: multiple plot-output as with the table functions

### ISSUE THREAD

**Issue by schnsn** [sjPlot/devel#58] opened 2015-08-04 13:39 UTC
Hello,
First of all: thank you for this really helpful package. ^^

With the table functions it's really easy to pipe a dataframe that has multiple variables into the `sjt.frq` function and have them printed, like so:

``` R
dat %>%
  select(var_1:var_n) %>%
  sjt.frq(file = "./nice_tables.html")
```

With `sjp.frq` however this is not possible because the parameter `varCount` expects a single vector. 
It would be really nice to have a file parameter in sjp.frq, basically a wrapper for the PDF-output (see code below) and to be able to hand it a dataframe with multiple variables. 
(the PDF-output was taken from your tutorial in https://strengejacke.wordpress.com/2013/02/25/simplify-frequency-plots-with-ggplot-in-r-rstats/ )

``` R
outputPDFPath <- c("/Users/danielludecke/Desktop/frequencies.pdf")
pdf(file=outputPDFPath)
from <- 291 # start first chart with variable (column) no. 291
to <- 343 # finish with variable (column) no. 343
for (j in from:to) {
  print(sjp.grp(gemo[,j],
          title = gemo_vars[j],
          axisLabels.x=gemo_label[[j]])
  print(to-j) # print progress to console
}
dev.off()
```

**Comment by sjPlot** [comment] 2016-02-13 19:10
Seems to be that https://github.com/sjPlot/devel/issues/73 is a duplicate of this issue, so I'll close this one and keep track of these two requests in the other issue.

**Closed by sjPlot** 2016-02-13 19:10 UTC
