### ISSUE TITLE
`sjt.lm` does not handle models without intercept

### ISSUE THREAD

**Issue by joelgombin** [sjPlot/devel#139] opened 2016-07-07 15:48 UTC
See this minimal example:

``` r
library(sjPlot)
x <- rnorm(100, 0, 1)
y <- x + rnorm(100,0,0.1)
df <- data.frame(x = x, y = y)
mod1 <- lm(y ~ x, data = df)
mod2 <- lm(y ~ 0 + x, data = df)

sjt.lm(mod1)
sjt.lm(mod2)
#> Error in apply(all.coefs, 1, function(x) length(unique(x))): dim(X) must have a positive length
```

**Comment by sjPlot** [comment] 2016-07-07 18:37
Possible duplicate of https://github.com/sjPlot/devel/issues/78

**Closed by sjPlot** 2016-07-07 18:37 UTC
