### ISSUE TITLE
a chi-square test issue: inconsistent results

### ISSUE THREAD

**Issue by frankcsliu** [sjPlot/devel#81] opened 2015-12-21 07:35 UTC
Hi, Daniel, 

I found that the computing results from sjt.xtab is different from those computed by chisq.test {base} and CrossTable() {gmodels}, as illustrated by the screenshot. Could you please check this issue? Thanks. 

Frank Liu
![2015-12-21_15-30-12](https://cloud.githubusercontent.com/assets/12545793/11925631/778e8880-a7f8-11e5-907d-186ff8846e8f.png)

**Comment by sjPlot** [comment] 2015-12-26 10:12
Do you have a reproducible example? For me, this seems to be ok:

    library(sjPlot)
    library(sjmisc)
    data(etc)
    sjt.xtab(efc$e16sex, efc$e42dep)
    chisq.test(table(efc$e16sex, efc$e42dep))

**Comment by frankcsliu** [comment] 2015-12-30 08:48
I double check with the student's work. We found it was a mistake. I am so sorry for the confusion.

**Comment by sjPlot** [comment] 2016-01-02 12:01
Ok, so I close this issue?

**Closed by sjPlot** 2016-01-02 12:01 UTC
