### ISSUE TITLE
Error in sjp.glmer(), type ="ri.pc"

### ISSUE THREAD

**Issue by jeroenclaes** [sjPlot/devel#13] opened 2015-03-27 17:31 UTC
I have a model with the following formula:

model_LH<- glmer(Tipo ~  Co.2.Pr + Education  + Negation + Pr.2.Pr + Typical.Action.Chain.Pos + Style*Tense +(1 + Co.2.Pr | Muestra)+ (1 + Negation | Muestra) +(1 + Typical.Action.Chain.Pos| Muestra)+ (1 | Nombrelema), data=datalh, family="binomial", control=glmerControl(optimizer="bobyqa"))

When I run
sjp.glmer(model_LH,   type = "ri.pc", show.se = TRUE)

I get the following error:
Error in `$<-.data.frame`(`*tmp*`, "xbeta", value = numeric(0)) : 
  replacement has 0 rows, data has 2093

**Comment by sjPlot** [comment] 2015-03-28 07:08
Would it be possible to send me some sample data, or the fitted model object saved from the environment (`save(model_LH, file = "model_lh.RData")`), via email? I haven't worked with multiple random intercepts and slopes yet, so there might be a bug when plotting predicted probabilities for various random intercepts...

**Comment by jeroenclaes** [comment] 2015-03-28 08:22
Please find attached the data and model object you requested

Jeroen Claes, PhD
Bresstraat 14/2
2018 Antwerpen
(+32) 472 57 32 24 
http://www.jeroenclaes.be <http://www.jeroenclaes.be/> 
Linkedin <http://be.linkedin.com/in/jeroenclaes> - Google Scholar <https://scholar.google.be/citations?user=qwrRh4QAAAAJ&hl=> - Academia <http://independent.academia.edu/JeroenClaes>

**Comment by sjPlot** [comment] 2015-03-28 17:47
Which version of the package sjPlot do you use? I can't reproduce this bug, all plots are shown (however, a takes _very_ long due to many coefficients and grouping levels).

**Comment by jeroenclaes** [comment] 2015-03-28 18:00
I tried both the cran version and the developer github version,  both gave
me the same issue with the code on the package website. I  will try on
Monday to update the package and I will let you know if that solves the
issue.

Thanks for looking into it.

Jeroen Claes, PhD
Bresstraat 14/2
2018 Antwerpen

Sent from a mobile device. Please excuse errors and/or brevity
Op 28-mrt.-2015 18:47 schreef "Daniel Lüdecke" <notifications@github.com>:

**Comment by sjPlot** [comment] 2015-03-28 18:27
What about the other packages? Are lme4 and arm up to date?

**Comment by jeroenclaes** [comment] 2015-03-29 11:04
I updated the lme4 and arm package and re-ran the code. I get the same error:
Error in `$<-.data.frame`(`*tmp*`, "xbeta", value = numeric(0)) : 
  replacement has 0 rows, data has 2093

**Comment by sjPlot** [comment] 2015-03-29 11:50
which version of sjPlot do you exactly use? Do you get a traceback / error call with some information at which point (code line) in the function call the error occurs? RStudio sometimes offers you a traceback on error calls.

**Comment by jeroenclaes** [comment] 2015-03-30 07:04
I updated to 1.6 and updated all other packages too, it seems to work now. Thanks for looking into it!

**Comment by sjPlot** [comment] 2015-03-30 08:17
Ok, so I may close this issue? Btw, latest sjPlot should be 1.7 (perhaps it was a typo?).
I also recommend using the `vars` parameter and plot selected variables only at first. Plotting all coefficients for all random intercept levels may take some time. ;-)

**Closed by sjPlot** 2015-03-30 08:17 UTC
