### ISSUE TITLE
Better integration of sjt functions for rmarkdown/rnotebooks

### ISSUE THREAD

**Issue by methodds** [sjPlot/devel#175] opened 2016-12-12 12:25 UTC
Hi,

can you please briefly explain what would be necessary for a better integration of ``sjt.`` functions in rmarkdown/rnotebook documents? 

While the current implementation with ``$knitr`` and ``ǹo.output=T`` works, it is a little bit annoying to use. Is there a way to make such functions behave like datatables from ``DT``? Using the following syntax in an rmarkdown/rnotebook document always shows the corresponding dataframe (in rnotebooks even directly inline) without the need of specifying any further options:

```
m = data.frame(a = 1, b = 2, c = 3)
DT::datatable(m)
```

**Comment by sjPlot** [comment] 2016-12-12 14:43
Possible duplicate of https://github.com/sjPlot/devel/issues/12

**Closed by sjPlot** 2016-12-12 14:43 UTC
