### ISSUE TITLE
`emm`

### ISSUE THREAD

**Issue by rubenarslan** [sjPlot/devel#34] opened 2015-05-19 17:31 UTC
I get the following error message with type='emm':

```
library(lme4); library(lmerTest); library(effects); library(sjPlot)
lme4::lmer(`Short term attractiveness` ~ Cue * gFaktor_Mann  +  (1|ID_Frau), data = comb) -> m1
sjp.int(fit = m1, plevel = 1,type ="emm")
```
> Computing approximate p-values via Wald chi-squared test...
Error in `colnames<-`(`*tmp*`, value = c("x", "y", "grp", "l.ci", "u.ci",  : 
  'names' attribute [6] must be the same length as the vector [5]

**Comment by sjPlot** [comment] 2015-05-19 18:19
Do you have a data set for a reproducible example?

**Comment by rubenarslan** [comment] 2015-05-19 19:51
Any data will do.

```r
library(lme4); library(sjPlot)
data(sleepstudy)
sleepstudy$mod = rnorm(nrow(sleepstudy))
fm2 <- lmer(Reaction ~ Days*mod + (1|Subject), sleepstudy)
summary(fm2)
sjp.int(fm2,plevel=1, type = 'emm')
```

**Comment by sjPlot** [comment] 2015-05-19 20:23
I'm not sure why, but `lmerTest::lsmeans` does not return any values...
Check `lmerTest::lsmeans(fm2)`

However, this works:

    library(sjmisc)
    data(efc)
    # create data frame with variables that should be included
    # in the model
    mydf <- data.frame(burden = efc$neg_c_7,
                       sex = efc$c161sex,
                       education = efc$c172code,
                       groups = efc$e15relat)
    # convert gender predictor to factor
    mydf$sex <- factor(mydf$sex)
    mydf$education <- factor(mydf$education)
    mydf$groups <- factor(mydf$groups)
    # name factor levels and dependent variable
    levels(mydf$sex) <- c("female", "male")
    levels(mydf$education) <- c("low", "mid", "high")
    mydf$burden <- set_var_labels(mydf$burden, "care burden")
    # fit "dummy" model
    fit <- lme4::lmer(burden ~ education*sex + (1|groups), data = mydf)
    summary(fit)
    
    sjp.int(fit, type = "emm")
    sjp.int(fit, type = "emm", plevel = 1)

**Comment by sjPlot** [comment] 2015-05-19 20:27
Ok, it seems that both predictors need to be `factor`s.

**Comment by rubenarslan** [comment] 2015-05-19 20:31
Don't think this is all, see

```r
example(lmerTest::lsmeans)
m <- lmer(Coloursaturation ~ TVset*Picture + (1|Assessor), data=TVbo)
sjp.int(m,type='emm')
```

The lsmeans example in lmerTest breaks on its own, maybe forward this to the creator?

**Comment by sjPlot** [comment] 2015-05-19 21:00
Where does it break? `lmerTest::lsmeans(m, "TVset:Picture")` works for me.

**Comment by sjPlot** [comment] 2015-05-19 21:56
I'll close this issue as it's not an issue of sjPlot, and additionally sjp.int now warns if predictors are not `factor`s. If you think that there still might be an sjPlot-issue with this, feel free to re-open this issue.

**Closed by sjPlot** 2015-05-19 21:56 UTC

**Comment by rubenarslan** [comment] 2015-05-20 07:49
should I raise these issues with the lmerTest and effects package dev or will you? not sure of the proper channels

**Comment by sjPlot** [comment] 2015-05-20 17:12
Maybe you should, because I can't figure out or reproduce your issue, so I'm not sure which bug exactly to report about...

    m <- lmer(Coloursaturation ~ TVset*Picture + (1|Assessor), data=TVbo)
    sjp.int(m,type='emm')

works for me w/o any error message.
